app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::pattern('id', '[0-9]+');
Route::pattern('touchpoint_id', '[0-9]+');

Route::get('update-patientID', 'SpecialController@transferID');

Route::get('/', 'admin\UserController@showLogin');
Route::post('/', 'admin\UserController@postLogin');
Route::post('login', 'admin\UserController@postLogin');
Route::get('logout', 'admin\UserController@showLogout');
Route::get('password/reset', 'admin\PasswordController@showReset');
Route::post('password/reset', 'admin\PasswordController@postReset');

// Authentication required
Route::group(array('before' => 'auth|auth.current-password'), function()
{
		//Debug
		Route::get('debug', 'admin\DebugController@index');
		//Dashboard
		Route::get('dashboard', 'admin\DashboardController@index');
		//Location Clinic
		Route::get('clinic-locations', 'admin\PatientDirectoryController@clinicLocations');
		//Reports
		Route::post('reports/set', array('as' => 'reports.set', 'uses' => 'admin\ReportController@setLocation'));
		Route::post('reports/state', array('as' => 'reports.state', 'uses' => 'admin\ReportController@setState'));
		Route::get('reports', 'admin\ReportController@index');
		Route::post('reports/download', 'admin\ReportController@download');
		Route::get('reports/debug', 'admin\ReportController@debug');
		// Touchpoint
		Route::get('patient-directory/touchpoint/{id}/create', array('as' => 'patient-directory.touchpoint.create', 'uses' => 'admin\TouchpointController@create'));
		Route::post('patient-directory/touchpoint', array('as' => 'patient-directory.touchpoint.store', 'uses' => 'admin\TouchpointController@store'));
		Route::get('patient-directory/touchpoint/{id}', array('as' => 'patient-directory.touchpoint.show ', 'uses' => 'admin\TouchpointController@show'));
		Route::get('patient-directory/touchpoint/{id}/{touchpoint_id}/edit', array('as' => 'patient-directory.touchpoint.edit', 'uses' => 'admin\TouchpointController@edit'));
		Route::put('patient-directory/touchpoint/{id}/{touchpoint_id}', array('as' => 'patient-directory.touchpoint.update', 'uses' => 'admin\TouchpointController@update'));
		Route::get('patient-directory/touchpoint/{id}/{touchpoint_id}', array('as' => 'patient-directory.touchpoint.touchpoint', 'uses' => 'admin\TouchpointController@touchpoint'));

		//Route::get('patient-directory/touchpoint/{id}/unable', array('as' => 'patient-directory.touchpoint.unable', 'uses' => 'admin\TouchpointController@unable'));
		Route::post('patient-directory/touchpoint/unable', array('as' => 'patient-directory.touchpoint.unable', 'uses' => 'admin\TouchpointController@unable'));


		// Directory
		Route::post('patient-directory/set', array('as' => 'patient-directory.set', 'uses' => 'admin\PatientDirectoryController@setLocation'));
		Route::post('patient-directory/state', array('as' => 'patient-directory.state', 'uses' => 'admin\PatientDirectoryController@setState'));
		Route::get('patient-directory/download', array('as' => 'patient-directory.download', 'uses' => 'admin\PatientDirectoryController@download'));
		Route::post('get-by-id', 'admin\PatientDirectoryController@getPatientById');
		Route::get('patient-directory/{id}/delete', 'admin\PatientDirectoryController@deleteRound');
		Route::resource('patient-directory', 'admin\PatientDirectoryController');
		// Search
		Route::get('search', 'admin\SearchController@index');

		// CMS Content Menu
		Route::group(array('prefix' => 'admin'), function()
		{
			//Admin
			Route::get('/', 'admin\AdminController@index');
			// Location
			Route::post('locations/set', array('as' => 'admin.locations.set', 'uses' => 'admin\LocationController@setLocation'));
			Route::resource('locations', 'admin\LocationController');
			// Insurance
			Route::resource('insurers', 'admin\InsurerController');
			// Users
			Route::post('users/updatepassword', array('as' => 'admin.users.updatepassword', 'uses' => 'UserController@updatepassword'));
			Route::post('users/{id}/unlock', ['as' => 'admin.users.unlock', 'uses' => 'admin\UserController@unlockUser']);
			Route::resource('users', 'admin\UserController');

		});
});

//Password
Route::post('password/refresh', 'admin\PasswordController@refreshPassword');
Route::get('password/refresh', 'admin\PasswordController@refresh');
Route::group(array('before' => 'auth|auth.current-password|auth.admin'), function()
{
Route::get('reports/api/key/generate', 'APIController@keypage');
Route::post('reports/api/key/generate', 'APIController@generateKey');
});
Route::post('reports/api/create-link', 'APIController@createLink');
Route::get('reports/api/generate', 'APIController@generate');
Route::get('reports/api', 'APIController@index');

//API Calls
Route::get('api/{table}/{apikey}', function($table = null, $apikey){
	if($apikey == '41a9l2334104KBO') {
		if($table == 'locations') {
			return Location::exclude(['photo'])->get();
		} elseif($table == 'insurers') {
			return Insurer::all();
		} elseif($table == 'patient-touchpoint') {
			return DB::table('patient_touchpoint')->get();
		} elseif($table == 'patients-proto') {
			return Patient::exclude(['first_name', 'last_name', 'address', 'city', 'state', 'zip', 'phone', 'alternate_phone', 'email', 'notes', 'photo', 'patient_state'])->get();
		} elseif($table == 'locations-proto') {
			return Location::exclude(['photo'])->get();
		} elseif($table == 'patients') {
			return Patient::exclude(['first_name', 'last_name', 'address', 'city', 'state', 'zip', 'phone', 'alternate_phone', 'email', 'notes', 'photo', 'patient_state'])->get();
		} elseif($table == 'touchpoints') {
			return Touchpoint::all();
		} 
		return '<p style="color:#fff;font-family:Helvetica, Arial, sans-serif;font-size:2em;font-weight:300;background:#fff; display:block;text-align:center; padding:15px;"><img style="margin-left:-10px;" src="http://touchpoint.legacyheartcare.com/library/img/logo-lhc.png" alt="" /><br /><br /> <span style="background:#D84348; padding:5px;">No Such Table Exists</span></p>';
	} 
	
	return '<p style="color:#fff;font-family:Helvetica, Arial, sans-serif;font-size:2em;font-weight:300;background:#fff; display:block;text-align:center; padding:15px;"><img style="margin-left:-10px;" src="http://touchpoint.legacyheartcare.com/library/img/logo-lhc.png" alt="" /><br /><br /> <span style="background:#D84348; padding:5px;">Incorrect API Key</span</p>';
	
});


// Help

Route::get('help', function(){
	return View::make('admin/pages/help');
});

app/models/Patient.php
<?php

use Illuminate\Support\Facades\URL;
class Patient extends Eloquent {

	protected $fillable = [];

	protected $table = 'patients';
	protected $columns = array('id','patient_	id','first_name', 'last_name', 'date_of_birth', 'touchpoint_snooze', 'touchpoint_progress', 'touchpoint_start_date', 'touchpoint_end_date', 'location_id', 'treatment_completion', 'cardiologist_first_name', 'cardiologist_last_name', 'insurer_id', 'secondary_insurer_id', 'address', 'city', 'state', 'zip', 'phone', 'alternate_phone', 'email', 'notes', 'photo', 'patient_state', 'created_at', 'updated_at'); // add all columns from you table

	public function scopeExclude($query,$value = array()) 
	{
	    return $query->select( array_diff( $this->columns,(array) $value) );
	}

	public function getNameAttribute()
	{
		return $this->first_name.' '.$this->last_name;
	}

	public function getStateAttribute()
	{
		$states = array('1' => 'Active', '2' => 'Archive', '3' => 'Expired', '4' => 'Incorrect');
		return $states[$this->patient_state];
	}

	public function getDates()
	{
	    return array('created_at', 'updated_at', 'date_of_birth', 'touchpoint_start_date', 'touchpoint_end_date', 'treatment_completion');
	}

	public function touchpoints()
    {
        return $this->belongsToMany('Touchpoint')->withPivot('touchpoint_id');;
    }

    public function insurer()
    {
        return $this->belongsTo('Insurer');
    }

    public function location()
    {
        return $this->belongsTo('Location');
    }

    
	public function deletePhoto($filename) {

		if( File::exists( public_path() . '/images/locations/' . $filename) && !empty($filename) )
		{
			File::delete(public_path() . '/images/locations/' . $filename);

			return true;
		}

		return false;
	}

	public function fullName()
	{
		return $this->first_name . ' ' . $this->last_name;
	}


	public function fullDoctorName()
	{
		return $this->cardiologist_first_name . ' ' . $this->cardiologist_last_name;
	}

	public function progress()
	{
		$past = false;
		$rounds = $this->number_of_rounds;	
		$patient_records = Patient::where('patient_id', $this->patient_id)->orderby('created_at', 'desc')->lists('id');


		$html = '<div class="progress touchpoint-progress">';

		$progress = array('0' => '30 Day', '1' => '90 Day', '2' => '6 months', '3' => '1 year', '4' => '2 years');

		$urlArray = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
		$segments = explode('/', $urlArray);
		$numSegments = count($segments);
		$currentSegment = $segments[$numSegments - 1];
		$id = $currentSegment;
		$create = true;
		if($rounds > 0 && ($this->id != $patient_records[0])) {
			$past = true;
			$create = false;
		}
		$latest_touchpoint = $this->touchpoints()->first() ? date('Y-m-d H:i:s', strtotime($this->touchpoints()->orderby('created_at', 'desc')->first()->created_at)) : date('Y-m-d H:i:s');
		for ( $i=0; $i < 5; $i++ ) {
			$progress_number = $progress[$i];
			if(($i == 1) && ($this->touchpoint_progress >= 1) &&
				(date('Y-m-d H:i:s', strtotime($this->created_at)) < date('Y-m-d H:i:s', strtotime('2018-04-16 00:00:00'))) && ($latest_touchpoint < date('Y-m-d H:i:s', strtotime('2018-04-16 00:00:00')))) {
				$progress_number = '60 Day';
			}
			if( $i < $this->touchpoint_progress ) {
				if($id == $this->touchpoints[$i]->id) {
					$html .= '<div class="progress-bar progress-bar-current" style="width: 20%">' . $progress_number . '</div>';
				} else {
					$html .= '<div class="progress-bar progress-bar-past" style="width: 20%"><a target="_blank" href="'.(URL::to('patient-directory/touchpoint/' . $this->id . '/' . $this->touchpoints[$i]->id)).'">' . $progress_number . '</a></div>';
				}

			} else {
				if($create && date('Y-m-d') >= date('Y-m-d', strtotime($this->touchpoint_end_date)) && $this->touchpoint_progress <= 4) {
					$html .= '<div class="progress-bar progress-bar-future" style="width: 20%"><a href="'.URL::to('/patient-directory/touchpoint/'. $this->id . '/create').'">' . $progress_number . '</a></div>';
					$create = false;
				} else {
					$html .= '<div class="progress-bar progress-bar-future" style="width: 20%">' . $progress_number . '</div>';
				}
			}
		}

		$html .= '</div><hr />';

		return $html;

	}

	public function progressCreate()
	{

		$html = '<div class="progress touchpoint-progress">';

		$progress = array('0' => '30 Day', '1' => '90 Day', '2' => '6 months', '3' => '1 year', '4' => '2 years');
		$create = true;
		$latest_touchpoint = $this->touchpoints()->first() ? date('Y-m-d H:i:s', strtotime($this->touchpoints()->orderby('created_at', 'desc')->first()->created_at)) : date('Y-m-d H:i:s');
		for ( $i=0; $i < 5; $i++ ) {
			$progress_number = $progress[$i];
			if(($i == 1) && ($this->touchpoint_progress >= 1) &&
				(date('Y-m-d H:i:s', strtotime($this->created_at)) < date('Y-m-d H:i:s', strtotime('2018-04-16 00:00:00'))) && ($latest_touchpoint < date('Y-m-d H:i:s', strtotime('2018-04-16 00:00:00')))) {
				$progress_number = '60 Day';
			}
			if($i == $this->touchpoint_progress && $this->touchpoint_snooze > 0 ) {
				$html .= '<div class="progress-bar progress-bar-future" style="width: 20%"><a href="'.URL::to('/patient-directory/touchpoint/'. $this->id . '/create').'">' . $progress_number . '</a></div>';
			}else if( $i < $this->touchpoint_progress ) {
				$html .= '<div class="progress-bar progress-bar-past" style="width: 20%"><a target="_blank" href="'.(URL::to('patient-directory/touchpoint/' . $this->id . '/' . $this->touchpoints[$i]->id)).'">' . $progress_number . '</a></div>';
			} else {
				if($create) {
					$html .= '<div class="progress-bar progress-bar-current" style="width: 20%">' . $progress_number . '</div>';
					$create = false;
				} else {
					$html .= '<div class="progress-bar progress-bar-future" style="width: 20%">' . $progress_number . '</div>';
				}
			}
		}

		$html .= '</div><hr />';

		return $html;
	}

	public function touchpointProgress($small = null, $past = null)
	{

		$html = '';
		//check for pre april 2018 push so that we can say they are "60 day"
		$tp_1 = '90 Day';
		$progress = array('0' => '30 Day', '1' => $tp_1, '2' => '6 months', '3' => '1 year', '4' => '2 years');
		$latest_touchpoint = $this->touchpoints()->first() ? date('Y-m-d H:i:s', strtotime($this->touchpoints()->orderby('created_at', 'desc')->first()->created_at)) : date('Y-m-d H:i:s');
		for ( $i=0; $i < 5; $i++ ) {
			$progress_number = $progress[$i];
			if(($i == 1) && ($this->touchpoint_progress >= 1) &&
				(date('Y-m-d H:i:s', strtotime($this->created_at)) < date('Y-m-d H:i:s', strtotime('2018-04-16 00:00:00'))) && ($latest_touchpoint < date('Y-m-d H:i:s', strtotime('2018-04-16 00:00:00')))) {
				$progress_number = '60 Day';
			}
			if($i == $this->touchpoint_progress && $this->touchpoint_snooze > 0 ) {
					if($past) {
						$html .= '<a href="#" class="btn btn-default inactive '.($small ? 'btn-xs' : null).'">' . $progress_number . '</a>';
					} else {
					$html .= '<a href="'.(URL::to('patient-directory/touchpoint/'. $this->id . '/create')).'" class="btn btn-warning '.($small ? 'btn-xs' : null).'">' . $progress_number . '</a>';
					}
			}else if( $i < $this->touchpoint_progress ) {
				if($this->touchpoints[$i]->touchpoint_complete == 0) {
					if($this->touchpoints[$i]->automated == 1) {
						$html .= '<a href="'.(URL::to('patient-directory/touchpoint/' . $this->id . '/' . $this->touchpoints[$i]->id)).'" class="btn btn-legacy '.($small ? 'btn-xs' : null).'">' . $progress_number . '</a>';
					} else {
						$html .= '<a href="'.(URL::to('patient-directory/touchpoint/' . $this->id . '/' . $this->touchpoints[$i]->id)).'" class="btn btn-danger '.($small ? 'btn-xs' : null).'">' . $progress_number . '</a>';
					}
				} else {
						$html .= '<a href="'.(URL::to('patient-directory/touchpoint/' . $this->id . '/' . $this->touchpoints[$i]->id)).'" class="btn btn-default '.($small ? 'btn-xs' : null).'">' . $progress_number . '</a>';
				}
				
			} else {

				$html .= '<a href="#" class="btn btn-default inactive '.($small ? 'btn-xs' : null).'">' . $progress_number . '</a>';

			}
		}

		return $html;
	}

	public function getInTheLastDateRangeAttribute()
	{
		$text = "In the last ";
		switch($this->touchpoint_progress) {
			case 0:
				return $text.'30 days';
				break;
			case 1:
				return $text.'2 months';
				break;
			case 2:
				return $text.'3 months';
				break;
			case 3:
				return $text.'6 months';
				break;
			case 4:
				return $text.'year';
				break;
			default:
				return null;
		}
	}

	public function getNumberOfRoundsAttribute()
	{
		return Patient::where('patient_id', $this->patient_id)->count();
	}

	public function getRoundsLabelAttribute()
	{
		return '<span class="rounds-label" style="border:1px solid #d0d0d0; color:#888; font-size:10px;background:#f2f2f2;padding:5px 10px;border-radius:9999px;">Round <strong style="color:#7E3832;font-size:12px;padding-left:5px;">'.$this->number_of_rounds.'</strong></span>';
	}

	public function scopelatestPatient($query)
	{
		$omit = [];
		self::chunk(50, function($patients) use ($omit){
			foreach($patients as $patient) {
				if(self::where('patient_id', $patient->patient_id)->orderby('created_at', 'desc')->first()) {
					$latest = self::where('patient_id', $patient->patient_id)->orderby('created_at', 'desc')->first()->id;
					if($patient->number_of_rounds > 1 && ($patient->id != $latest)) {
						array_push($omit, $patient->id);
					}
				}
			}
		});
		return $query->whereNotIn('id', $omit);
	}

	public static function getLargestAmountOfRounds($query){
		$rounds = [];
		foreach($query as $patient) {
			array_push($rounds, $patient->number_of_rounds);
		}
		return max($rounds);
	}
}

app/views/admin/pages/admin.blade.php
@extends('admin.layouts.master')

@section('title')
Admin
@stop

@section('head')

@stop

@section('content')
	<div class="row" id="admin-panels">
		<div class="col-sm-1"></div>
		<div class="col-sm-3 panel admin-locations">
			<h3>Locations</h3>
			<a class="btn btn-default" href="{{ URL::to('admin/locations') }}">view locations</a>
		</div>
		<div class="col-sm-1"></div>
		<div class="col-sm-3 panel admin-insurers">
			<h3>Insurers</h3>
			<a class="btn btn-default" href="{{ URL::to('admin/insurers') }}">view insurers</a>
		</div>
		<div class="col-sm-1"></div>
		<div class="col-sm-3 panel admin-users">
			<h3>Admins</h3>
			<a class="btn btn-default" href="{{ URL::to('admin/users') }}">view admins</a>
		</div>
	</div>
@stop

@section('script')
	
@stop

app/views/admin/pages/dashboard.blade.php
@extends('admin.layouts.master')

@section('title')
Clinic Locations
@stop

@section('head')

@stop

@section('content')
	<div class="location-list row">

		<div class="col-sm-10 col-sm-offset-1">
			<?php $i = 0; ?>
	   	  	@if ($locations->count())
                @foreach(array_chunk( $locations->all(), 2 ) as $location)
                    <div class="row">
                        @foreach($location as $item)

                          <div class="col-sm-6 col-md-6 location">
						   	  <div class="location-container">
						   	  	  <div class="gradient">
							   	  	 
									<img src="{{ URL::asset('library/img/loc-gradient.png') }}" alt="" />
									<h1>{{ $item->name }}</h1>
						   	  	  </div>
							   	  <img src="{{ URL::asset('images/locations/'.$item->photo) }}" alt="" />
							   	  <div class="clear"></div>
							   	  
							   	  @if($pastdue[$i])
									<p class="audit overdue">{{ $pastdue[$i] }} TouchPoints Overdue</p>
								  @else
									<p class="audit overdue none">&nbsp;</p>  
								  @endif							   	  
							   	  
							   	  <div class="clear"></div>
							   	  <hr />
							   	  <div class="review">
							   	  {{ Form::open(array('route' => 'admin.locations.set')) }}
							   	  	{{ Form::hidden('location_id', $item->id) }}							   	  
							   	  	{{ Form::submit('View', array('class' => 'btn btn-primary pull-right')) }}
							   	  {{ Form::close() }}
							   	  <p class="eligible">{{ $coming[$i] }} TouchPoints</p>
							   	  </div>
							   	  <div class="clear"></div>
							   	  <!--
							   	  DEV NOTE : THE FOLLOW COMMENT HIDES THE PROGRESS BAR
							   	  <hr />
							   	  <div class="progress">
								   	  <div class="progress-bar" role="progressbar" aria-valuenow="18" aria-valuemin="0" aria-valuemax="100" style="width: 18%;"></div>
								   	  <span>18%</span>
							   	  </div>
							   	  -->
						   	  </div>
					   	  </div>
					   	<?php $i++; ?>
                        @endforeach
                    </div>
                @endforeach
              @else
                <p>No locations were found.</p>
            @endif
	
		   	  
		</div>

	</div>
@stop

@section('script')
	
@stop

app/views/admin/pages/login.blade.php
@extends('admin.layouts.login')

@section('title')
Login
@stop

@section('head')

@stop

@section('content')

	<div class="row">
    	<div class="col-sm-5">
	    	<h1>
			   	<small>welcome to</small><br />TouchPoint
		   	</h1>
    	</div>

    	
    	<!-- LOGIN FORM -->

	    <!-- <form action="" class="login col-sm-7"> -->
	    {{ Form::open(array('class' => 'form-signin login col-sm-7', 'url' => URL::to('login'))) }}
	    	<div class="row">
		    	<p class="col-sm-8 col-sm-offset-2">
			    	login to get started
		    	</p>
		    	<div class="col-sm-12">
	    		@if(Session::get('locked_out') && Session::get('locked_out') == 1)
	    			@include('admin.pages.partials.locked-out')
	    		@else
	    			@include('admin.pages.partials.login')
	    		@endif
	    	</div>
	    <!-- </form> -->
	    {{ Form::close() }}
	    <!-- ///END LOGIN FORM -->
	    <div class="clear"></div>
    </div>
@stop

@section('scripts')
	<script>
		$(function() {
			$('input[name=email]').focus();
		});
	</script>
@stop

app/views/admin/pages/queues.blade.php
@extends('admin.layouts.master')

@section('title')
Clinic Locations
@stop

@section('head')

@stop

@section('content')
	<h1>{{ $location->name }}</h1>
	<p>{{ $location->description }}</p>
	<br /><br />
	
	<?php $touchpoints = Config::get('constants.TOUCHPOINT'); ?>
	
	@if($patients_pastdue->count())

	<h1>PAST DUE</h1>

	<table class="table table-striped queue past-due">
	   	<thead>
		   	<tr>
			   	<th colspan="2">Name</th>
			   	<th>Phone</th>
			   	<th>Round</th>
			   	<th>TouchPoint</th>
			   	<th>Contact By</th>
			   	<th>Actions</th>
		   	</tr>
	   	</thead>
	   	<tbody>
	   		<!-- DEV NOTE : PATIENT RECORD ROW -->

	   		

	   		@foreach($patients_pastdue as $pastdue)
	   			<tr>
			   		<td>
			   		    @if(!empty($pastdue->photo))	
							<img src="/images/patients/{{$pastdue->photo}}" width="40" alt="">
						@else
							<img src="/images/patients/bg-generic-ppl.jpg" width="40" alt="">
						@endif
			   		</td>
				   	<td>{{ $pastdue->fullName() }}</td> <!-- DEV NOTE : PATIENT NAME -->
				   	<td>{{ $pastdue->phone }}</td> <!-- DEV NOTE : PATIENT PHONE NUMBER -->
				   	<td>{{ $pastdue->rounds_label }}</strong></td>
				   	<td>{{ ($pastdue->touchpoint_progress == 1) && (date('Y-m-d H:i:s', strtotime($pastdue->touchpoints()->orderby('created_at', 'desc')->first()->created_at)) < date('Y-m-d H:i:s', strtotime('2018-04-16 00:00:00'))) ? '60 Days' : $touchpoints[$pastdue->touchpoint_progress] }}</td> <!-- DEV NOTE : PATIENT'S CURRENT TOUCHPOINT STATUS -->
				   	<td><span>{{ $pastdue->touchpoint_end_date->format('F j, Y') }}</span></td> <!-- DEV NOTE : DATE DETERMINED BY TOUCHPOINT STATUS -->
			   		<td>
				   		<a href="{{ URL::to('patient-directory/touchpoint/'.$pastdue->id.'/create') }}" class="btn btn-primary">Input TouchPoint</a> <!-- DEV NOTE : TAKES USER TO CURRENT TOUCHPOINT RECORD FOR THE PATIENT -->
			   		</td>
			   	</tr>
	   		@endforeach

		   	<!-- ///END DEV NOTE : PATIENT RECORD ROW -->
		   
	   	</tbody>
	</table>

	@endif

		@if( $patients_coming->count() )

		<h1>UPCOMING</h1>

		<table class="table table-striped queue">
		   	<thead>
			   	<tr>
				   	<th colspan="2">Name</th>
				   	<th>Phone</th>
				   	<th>Round</th>
				   	<th>TouchPoint</th>
				   	<th>Contact By</th>
				   	<th>Actions</th>
			   	</tr>
		   	</thead>
		   	<tbody>
		   		@foreach($patients_coming as $coming)
			   	<tr>
			   		<td>
				   		@if(!empty($coming->photo))	
							<img src="/images/patients/{{$coming->photo}}" width="40" alt="">
						@else
							<img src="/images/patients/bg-generic-ppl.jpg" width="40" alt="">
						@endif
			   		</td>
				   	<td>{{ $coming->fullName() }}</td>
				   	<td>{{ $coming->phone }}</td>
				   	<td>{{ $coming->rounds_label }}</td>
				   	<td>{{ $touchpoints[$coming->touchpoint_progress] }}</td>
				   	<td><span>{{ $coming->touchpoint_end_date->format('F j, Y') }}</span></td>
			   		<td>
				   		<a href="{{ URL::to('patient-directory/touchpoint/'.$coming->id.'/create') }}" class="btn btn-primary">Input TouchPoint</a>
			   		</td>
			   	</tr>
			   	@endforeach
		   	</tbody>
		</table>

		@else
					
		<div class="alert alert-info">No upcoming TouchPoints for this location.</div>	
				
		@endif
	

@stop

@section('script')
	
@stop