app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::pattern('id', '[0-9]+');
Route::pattern('touchpoint_id', '[0-9]+');

Route::get('update-patientID', 'SpecialController@transferID');

Route::get('/', 'admin\UserController@showLogin');
Route::post('/', 'admin\UserController@postLogin');
Route::post('login', 'admin\UserController@postLogin');
Route::get('logout', 'admin\UserController@showLogout');
Route::get('password/reset', 'admin\PasswordController@showReset');
Route::post('password/reset', 'admin\PasswordController@postReset');

// Authentication required
Route::group(array('before' => 'auth|auth.current-password'), function()
{
		//Debug
		Route::get('debug', 'admin\DebugController@index');
		//Dashboard
		Route::get('dashboard', 'admin\DashboardController@index');
		//Location Clinic
		Route::get('clinic-locations', 'admin\PatientDirectoryController@clinicLocations');
		//Reports
		Route::post('reports/set', array('as' => 'reports.set', 'uses' => 'admin\ReportController@setLocation'));
		Route::post('reports/state', array('as' => 'reports.state', 'uses' => 'admin\ReportController@setState'));
		Route::get('reports', 'admin\ReportController@index');
		Route::post('reports/download', 'admin\ReportController@download');
		Route::get('reports/debug', 'admin\ReportController@debug');
		// Touchpoint
		Route::get('patient-directory/touchpoint/{id}/create', array('as' => 'patient-directory.touchpoint.create', 'uses' => 'admin\TouchpointController@create'));
		Route::post('patient-directory/touchpoint', array('as' => 'patient-directory.touchpoint.store', 'uses' => 'admin\TouchpointController@store'));
		Route::get('patient-directory/touchpoint/{id}', array('as' => 'patient-directory.touchpoint.show ', 'uses' => 'admin\TouchpointController@show'));
		Route::get('patient-directory/touchpoint/{id}/{touchpoint_id}/edit', array('as' => 'patient-directory.touchpoint.edit', 'uses' => 'admin\TouchpointController@edit'));
		Route::put('patient-directory/touchpoint/{id}/{touchpoint_id}', array('as' => 'patient-directory.touchpoint.update', 'uses' => 'admin\TouchpointController@update'));
		Route::get('patient-directory/touchpoint/{id}/{touchpoint_id}', array('as' => 'patient-directory.touchpoint.touchpoint', 'uses' => 'admin\TouchpointController@touchpoint'));

		//Route::get('patient-directory/touchpoint/{id}/unable', array('as' => 'patient-directory.touchpoint.unable', 'uses' => 'admin\TouchpointController@unable'));
		Route::post('patient-directory/touchpoint/unable', array('as' => 'patient-directory.touchpoint.unable', 'uses' => 'admin\TouchpointController@unable'));


		// Directory
		Route::post('patient-directory/set', array('as' => 'patient-directory.set', 'uses' => 'admin\PatientDirectoryController@setLocation'));
		Route::post('patient-directory/state', array('as' => 'patient-directory.state', 'uses' => 'admin\PatientDirectoryController@setState'));
		Route::get('patient-directory/download', array('as' => 'patient-directory.download', 'uses' => 'admin\PatientDirectoryController@download'));
		Route::post('get-by-id', 'admin\PatientDirectoryController@getPatientById');
		Route::get('patient-directory/{id}/delete', 'admin\PatientDirectoryController@deleteRound');
		Route::resource('patient-directory', 'admin\PatientDirectoryController');
		// Search
		Route::get('search', 'admin\SearchController@index');

		// CMS Content Menu
		Route::group(array('prefix' => 'admin'), function()
		{
			//Admin
			Route::get('/', 'admin\AdminController@index');
			// Location
			Route::post('locations/set', array('as' => 'admin.locations.set', 'uses' => 'admin\LocationController@setLocation'));
			Route::resource('locations', 'admin\LocationController');
			// Insurance
			Route::resource('insurers', 'admin\InsurerController');
			// Users
			Route::post('users/updatepassword', array('as' => 'admin.users.updatepassword', 'uses' => 'UserController@updatepassword'));
			Route::post('users/{id}/unlock', ['as' => 'admin.users.unlock', 'uses' => 'admin\UserController@unlockUser']);
			Route::resource('users', 'admin\UserController');

		});
});

//Password
Route::post('password/refresh', 'admin\PasswordController@refreshPassword');
Route::get('password/refresh', 'admin\PasswordController@refresh');
Route::group(array('before' => 'auth|auth.current-password|auth.admin'), function()
{
Route::get('reports/api/key/generate', 'APIController@keypage');
Route::post('reports/api/key/generate', 'APIController@generateKey');
});
Route::post('reports/api/create-link', 'APIController@createLink');
Route::get('reports/api/generate', 'APIController@generate');
Route::get('reports/api', 'APIController@index');

//API Calls
Route::get('api/{table}/{apikey}', function($table = null, $apikey){
	if($apikey == '41a9l2334104KBO') {
		if($table == 'locations') {
			return Location::exclude(['photo'])->get();
		} elseif($table == 'insurers') {
			return Insurer::all();
		} elseif($table == 'patient-touchpoint') {
			return DB::table('patient_touchpoint')->get();
		} elseif($table == 'patients-proto') {
			return Patient::exclude(['first_name', 'last_name', 'address', 'city', 'state', 'zip', 'phone', 'alternate_phone', 'email', 'notes', 'photo', 'patient_state'])->get();
		} elseif($table == 'locations-proto') {
			return Location::exclude(['photo'])->get();
		} elseif($table == 'patients') {
			return Patient::exclude(['first_name', 'last_name', 'address', 'city', 'state', 'zip', 'phone', 'alternate_phone', 'email', 'notes', 'photo', 'patient_state'])->get();
		} elseif($table == 'touchpoints') {
			return Touchpoint::all();
		} 
		return '<p style="color:#fff;font-family:Helvetica, Arial, sans-serif;font-size:2em;font-weight:300;background:#fff; display:block;text-align:center; padding:15px;"><img style="margin-left:-10px;" src="http://touchpoint.legacyheartcare.com/library/img/logo-lhc.png" alt="" /><br /><br /> <span style="background:#D84348; padding:5px;">No Such Table Exists</span></p>';
	} 
	
	return '<p style="color:#fff;font-family:Helvetica, Arial, sans-serif;font-size:2em;font-weight:300;background:#fff; display:block;text-align:center; padding:15px;"><img style="margin-left:-10px;" src="http://touchpoint.legacyheartcare.com/library/img/logo-lhc.png" alt="" /><br /><br /> <span style="background:#D84348; padding:5px;">Incorrect API Key</span</p>';
	
});


// Help

Route::get('help', function(){
	return View::make('admin/pages/help');
});

app/models/User.php
<?php

use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends Eloquent implements UserInterface, RemindableInterface {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password');

	/**
	 * Get the unique identifier for the user.
	 *
	 * @return mixed
	 */
	public function getAuthIdentifier()
	{
		return $this->getKey();
	}

	/**
	 * Get the password for the user.
	 *
	 * @return string
	 */
	public function getAuthPassword()
	{
		return $this->password;
	}

	/**
	 * Get the token value for the "remember me" session.
	 *
	 * @return string
	 */
	public function getRememberToken()
	{
		return $this->remember_token;
	}

	/**
	 * Set the token value for the "remember me" session.
	 *
	 * @param  string  $value
	 * @return void
	 */
	public function setRememberToken($value)
	{
		$this->remember_token = $value;
	}

	/**
	 * Get the column name for the "remember me" token.
	 *
	 * @return string
	 */
	public function getRememberTokenName()
	{
		return 'remember_token';
	}

	/**
	 * Get the e-mail address where password reminders are sent.
	 *
	 * @return string
	 */
	public function getReminderEmail()
	{
		return $this->email;
	}

	/**
	 * Get the full name.
	 *
	 * @return string
	 */
	public function fullName()
	{
		return $this->first_name . ' ' . $this->last_name;
	}

	public function getAccessLevelLabelAttribute()
	{
		switch($this->access_level) {
			case 0:
				return 'Administrator';
				break;
			case 1:
				return 'User';
				break;
			case 9:
				return 'Super Administrator';
				break;
		}
	}



}

app/controllers/admin/UserController.php
<?php namespace admin;

use BaseController;
use ModelNotFoundException;
use Auth;
use Input;
use View;
use Redirect;
use Validator;
use Str;
use User;
use Hash;
use Illuminate\Support\Facades\Session;

class UserController extends BaseController
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        if (Auth::user()->access_level >= 2) {
            $users = User::orderBy('id', 'DESC')->get();

            return View::make('admin.users.index', compact('users'));
        } else {
            return Redirect::to('/dashboard');
        }

        

        //$show = Input::get('a');
        //if($show == 'sort'){
            //return View::make('admin.users.sort', compact('users'));
        //} else {
               //return View::make('admin.users.index', compact('users'));
        //}
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        if (Auth::user()->access_level >= 2) {
            return View::make('admin.users.create');
        } else {
            return Redirect::to('/dashboard');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        $input  = Input::all();

        $rules = array(
            'first_name'	=>	'required',
            'last_name'	=>	'required',
            'email'	=>	'required|unique:users|email',
            'password' => strlen($input['password']) > 0 ? 'required|min:10|regex:/^.*(?=.*[a-zA-Z])(?=.*[0-9]).*$/' : ''
            );

        $v = Validator::make($input, $rules);

        if ($v->passes()) {
            $user = new User();
            $user->first_name = $input['first_name'];
            $user->last_name = $input['last_name'];
            $user->email = $input['email'];
            $user->active = $input['active'];
            $user->access_level = $input['access_level'];
            $user->password = Hash::make($input['password']);
            $user->reset_password = date('Y-m-d 00:00:00', strtotime('+1 year'));
            $user->save();

            return Redirect::to('admin/users')->withInput()->with('success', 'New User has been created successfully.');
        } else {
            return Redirect::to('admin/users/create')->withInput()->withErrors($v);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);

        return View::make('admin.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        return View::make('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update($id)
    {
        //
        
        $input  = Input::all();

        $rules = array(
            'first_name'	=>	'required',
            'last_name'	=>	'required',
            'email'	=>	'required|email',
            'password' => strlen($input['password']) > 0 ? 'min:10|regex:/^.*(?=.*[a-zA-Z])(?=.*[0-9]).*$/' : ''
            );

        $v = Validator::make($input, $rules);

        if ($v->passes()) {
            $user = User::find($id);
            $user->first_name = $input['first_name'];
            $user->last_name = $input['last_name'];
            $user->email = $input['email'];
            $user->active = $input['active'];
            $user->access_level = $input['access_level'];
            $password = $input['password'];
            if (!empty($password)) {
                $user->password = Hash::make($password);
                $user->reset_password = date('Y-m-d 00:00:00', strtotime('+1 year'));
            }
                
            $user->save();

            return Redirect::to('admin/users/'.$id.'/edit')->withInput()->with('success', 'User info has been updated successfully.');
        } else {
            return Redirect::to('admin/users/'.$id.'/edit')->withInput()->withErrors($v);
        }
    }


    /**
     * Update users password.
     *
     * @return Response
     */
    public function updatepassword()
    {
        //
        $input  = Input::all();

        $id = $input['id'];

        $rules = array(
            'password'			=>	'required|min:10',
            'password_confirm'		=>	'required|same:password',
            );

        $v = Validator::make($input, $rules);

        if ($v->passes()) {
            $user = User::find($id);
            $user->password = $input['password'];
            $user->reset_password = date('Y-m-d 00:00:00', strtotime('+1 year'));
            $user->save();

            return Redirect::to('admin/users/'.$id.'/edit')->withInput()->with('success', 'User password has been updated successfully.');
        } else {
            return Redirect::to('admin/users/'.$id.'/edit')->withInput()->withErrors($v);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //

        $user = User::find($id);

        $user->delete();

        return Redirect::to('admin/users')->with('success', 'User has been deleted.');
    }



    /**
     * Display a loing view.
     *
     * @return Response
     */
    public function showLogin()
    {
        return View::make('admin.pages.login');
    }

    /**
     * Log user from cms.
     *
     * @return Response
     */
    public function showLogout()
    {
        Auth::logout();

        return Redirect::to('/');
    }
    
    /**
     * Login user to cms.
     *
     * @return Response
     */
    public function postLogin()
    {
        $input  = Input::all();

        $rules = array(
        'email'			=>	'required|email',
        'password'		=>	'required',
    );
        $v = Validator::make($input, $rules);

        if ($v->fails()) {
            return Redirect::to('/')->withErrors($v);
        } else {

            // create our user data for the authentication
            $userdata = array(
                'email' => $input['email'],
                'password' => $input['password']
            );

            // attempt to do the login
            if (Auth::attempt($userdata)) {
                $user = User::where('email', $input['email'])->first();
                //if user has been cleared to get a password reset, then next attempt at logging in will redirect the user to the password reset functions
                if($user->restore == 1) {
                	Auth::logout();
                	Session::flash('restore', 'A Touchpoint Admin Team Member has allowed you to reset your password');
                	return Redirect::to('password/reset');
                }

                // if user is locked out, prevent authentication and show locked out content
                if($user->locked == 1) {
                	Auth::logout();
                	Session::flash('locked_out', 1);
                	return Redirect::to('/')->with('error', 'You are locked out because you failed to log in correctly 5 times');
                }
                
                // make sure user is set to normal state
                $user->login_attempts = 0;
                $user->locked = 0;
                $user->restore = null;
                $user->save();
                
                return Redirect::intended('dashboard');
            } else {
                // validation not successful, send back to form
                if (User::where('email', $input['email'])->first()) {
                    $user = User::where('email', $input['email'])->first();
                    $user->login_attempts = $user->login_attempts + 1;
                    $user->save();
                    if($user->restore == 1) {
                	Session::flash('restore', 'A Touchpoint Admin Team Member has allowed you to reset your password');
                	return Redirect::to('password/reset');
                	}
                	if($user->locked == 1) {
                	Session::flash('locked_out', 1);
	                }
                    if ($user->login_attempts < 5) {
                        Session::flash('login_attempts', 5 - $user->login_attempts);
                    } else {
                    	$user->locked = 1;
                    	$user->restore = null;
                    	$user->save();
                        Session::flash('locked_out', 1);
                    }
                }
                return Redirect::to('/')->with('error', 'Check your username or password');
                ;
            }
        }
    }

    public function unlockUser($id)
    {
    	$input = Input::all();
    	$user = User::find($id);
    	$user->restore = 1;
    	$user->save();
    	return Redirect::back()->with('success', 'User will able to reset their password.');
    }
}

app/views/admin/users/create.blade.php
@extends('admin.layouts.master')

@section('title')
User Create
@stop

@section('head')
	<link rel="stylesheet" href="{{ URL::asset('library/css/password.css') }}">
@stop

@section('content')
	<div class="row">
		<div class="col-sm-12">
			<br />
			<a href="{{ URL::to('admin/users') }}" class="btn btn-default"><i class="glyphicon glyphicon-chevron-left"></i> Back</a>
		</div>
	</div>
	<section class="row">
		
		<div class="col-sm-12">	
			<br />
			{{ Form::open(array('url' => 'admin/users', 'class' => 'form-admin', 'files' => true)) }}

				@if($errors->any())
					<div class="alert alert-danger">
						<ul>
							{{ implode('', $errors->all('<li class="error">:message</li>')) }}
						</ul>
					</div>
				@endif

				<div class="row">
					<div class="col-sm-12">
						<div class="form-group password-rules hidden">
							<div class="well">
								<strong>Your password must</strong><br>
								be a minimum of 10 characters <br>
								contain at least 1 uppercase character <em>(A-Z)</em><br>
								contain at least 1 numeral <em>(0-9)</em><br>
								container a special character <em>(ex: @$%)</em>

							</div>
						</div>
					</div>
					<div class="col-sm-6"> 
						<div class="form-group">
							{{ Form::label('first_name', 'First Name *') }}
							{{ Form::text('first_name', null, array('placeholder' =>'First Name', 'class' => 'form-control')) }}
						</div>
					</div>
					<div class="col-sm-6">
						<div class="form-group">
							{{ Form::label('last_name', 'Last Name *') }}
							{{ Form::text('last_name', null, array('placeholder' =>'Last Name', 'class' => 'form-control')) }}
						</div>
					</div>

					<div class="col-sm-6"> 
						<div class="form-group">
							{{ Form::label('email', 'Email *') }}
							{{ Form::text('email', null, array('placeholder' =>'Email', 'class' => 'form-control')) }}
						</div>
					</div>
					<div class="col-sm-6">
						<div class="form-group">
							{{ Form::label('password', 'Password') }}
							<input type="password" id="password" name="password" class="form-control" />
							
						</div>
					</div>
					<div class="col-sm-6">
						<div class="form-group">
							{{ Form::label('access_level', 'Access Level') }}
							<select name="access_level" class="form-control">
								<option value="0">Administrator</option>
								<option value="1">User</option>
								<option value="9">Super Administrator</option>
							</select>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="form-group">
							{{ Form::label('active', 'status') }}
							<select name="active" class="form-control">
								<option value="0">Inactive</option>
								<option value="1">Active</option>
							</select>
						</div>
					</div>
					
				</div>

				

				<div class="form-group pull-right">			
					{{ link_to('admin/users', 'Cancel',  array('class' => 'btn btn-danger')) }}
					{{ Form::submit('Create', array('class' => 'btn btn-primary')) }}
				</div>

			{{ Form::close() }}
					
		</div>
		
	 </section> <!-- /.container -->
@stop

@section('script')
	<script src="/js/vendor/summernote.min.js"></script>
	<script src="/js/vendor/holder.js"></script>
	<script src="{{ URL::asset('library/js/password.js') }}"></script>
	<script>
		$(document).ready(function(){
			$('#password').password({
				minimumLength: 10,
				showText: true, // shows the text tips
				animate: true, // whether or not to animate the progress bar on input blur/focus
				animateSpeed: 'fast', // the above animation speed
			});
			$(window).on('keyup', function(){
				var passwordLength = $('#password').val().length;
				if($('#password').val().length > 0) {
					$('.password-rules').removeClass('hidden');
					$('#password').on('password.score', function(e, score){
						if(score >= 68) {
							$('input[type="submit"]').removeClass('disabled');
						} else {
							$('input[type="submit"]').addClass('disabled');
						}
					});
				} else {
					$('.password-rules').addClass('hidden');
					$('input[type="submit"]').removeClass('disabled');
				}
			});
		});
	</script>
@stop

app/views/admin/users/index.blade.php
@extends('admin.layouts.master')

@section('title')
Admins
@stop

@section('content')
	<div class="row">
		<div class="col-sm-12">
			<br />
			<a href="{{ URL::to('admin') }}" class="btn btn-default"><i class="glyphicon glyphicon-chevron-left"></i> Back to Admin</a>
			<a href="{{ URL::to('admin/users/create') }}" class="btn btn-default"><i class="glyphicon glyphicon-plus-sign"></i> Create User Record</a>
		</div>
	</div>
	<section class="row">

		<div class="col-sm-12">
			<br />
			@if( Session::has('success') )
				<div class="alert alert-success alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					{{ Session::get('success') }}
				</div>
			@endif

			@if(!empty($users[0]))

			<div class="table-responsive">
				<table class="table table-striped table-hover">
				<thead>
				<tr>
					<th width="45%">Name</th>
					<th>Status</th>
					@if(Auth::user()->access_level == 9 && Auth::user()->active)
					<th>API Key</th>
					@endif
					<th>Access Level</th>
					<th>Locked Out</th>
					<th>Actions</th>
				</tr>
				</thead>
				<?php
					$status = Config::get('constants.STATUS');
				?>
				
				@foreach($users as $item)
					<tr>
						<td class="td_valign"><a href="/admin/users/{{ $item->id }}/edit">{{ $item->first_name }} {{ $item->last_name }}</a></td>
						<td class="td_valign">{{ $status[$item->active] }}</td>
						@if(Auth::user()->access_level == 9 && Auth::user()->active)
						<td style="vertical-align: middle;padding:0;position: relative;">
							@if((Auth::user()->id == $item->id || (Auth::user()->access_level == 9 && Auth::user()->active)) && APIKey::where('user_id' ,$item->id)->where('active', 1)->first())
								<code class="text-primary" style="display:inline-block;padding:10px;background:#FFF;">
											{{ APIKey::where('user_id' ,$item->id)->where('active', 1)->first()->key }}
										</code>
								@endif
						</td>
						@endif
						<td class="td_valign">{{ $item->access_level_label }}</td>
						<td class="td_valign">
							@if($item->locked == 1)
								@if($item->restore == 1)
								<a data-toggle="modal" data-target="#unlockUser{{ $item->id }}" class="btn btn-sm btn-info"><i class="glyphicon glyphicon-lock"></i> Pending Password Reset</a>
								@else
								<a data-toggle="modal" data-target="#unlockUser{{ $item->id }}" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-lock"></i> Locked Out</a>
								@endif
							@endif
							<!-- Modal -->
							<div class="modal fade" id="unlockUser{{ $item->id }}" tabindex="-1" role="dialog" aria-labelledby="unlockUser{{ $item->id }}">
							  <div class="modal-dialog" role="document">
							    <div class="modal-content">
							      <div class="modal-header">
							        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							        <h4 class="modal-title" id="myModalLabel">{{ $item->first_name.' '.$item->last_name }} Is Locked Out</h4>
							      </div>
							      <div class="modal-body">
										<p>
								        	This user will, on the next attempted login, be redirected to a password reset page. You can also share the following link via email to the user so that they can directly visit this page.
								        </p>
										<br>
										<span class="text-muted">Password Reset Page</span><br>
										<strong>{{ URL::to('password/reset') }}</strong>
							      </div>
							      <div class="modal-footer">
							      	@if($item->restore == 1)
							      	<div class="alert alert-info">
							      		The user is locked until they reset their password <button class="btn btn-default" data-dismiss="modal">Close</button>
							      	</div>							      	
							      	@else
							      	{{ Form::open(['route' => ['admin.users.unlock', $item->id]]) }}
							        
							        <button type="submit" class="btn btn-primary">Unlock User</button>
							        {{ Form::close() }}
							      	@endif
							      	
							      </div>
							    </div>
							  </div>
							</div>
						</td>
						<td class="text-center">
							<nobr>
								<a href="{{ URL::to('admin/users/'.$item->id.'/edit') }}" style="display: inline-block" class="btn btn-info btn-sm"><i class="glyphicon glyphicon-pencil"></i></a>
							<a href="{{ URL::to('admin/users/'.$item->id) }}" style="display: inline-block" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash"></i></a>
							</nobr>
						</td>
					</tr>
				@endforeach
													
				
			</table>
			</div>

			@else
				<div class="alert alert-info">No users were found.</div>
			@endif			
					
		</div> <!-- /.col-sm-12 -->
		
		
	 </section> <!-- /.row -->
@stop

@section('script')
<script>
	$('.delete').click( function (event) {
		var item = $(this);
		//bootbox.confirm("Are you sure delete?", function(result) {
		//	if(result){
		item.closest('tr').animate(
			{ opacity: 0 }, {
				duration: 400,
				easing: 'easeOutExpo',
				complete:  function() {
					item.closest('tr').remove();
				} 
			});
		//	}
		//});
				
		event.preventDefault();
	});
</script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script src="/js/vendor/jquery.ui.touch-punch.min.js"></script>
<script>
	$(function () {
		$(".list-group").sortable({
		    tolerance: 'pointer',
		    revert: 'invalid',
		    placeholder: 'placeholder-item',
		    forceHelperSize: true,

		    update: function(event, ui) {
		        order = $('.list-group').sortable("toArray");
		        $.ajax({
		        	type: "POST",
		            url: URL.base + '/admin/manage/staff/sort',
		            data: {order:order},
		            success: function(data)
					{
						console.log(data);
					}                     
		        });
		    }
		});
	});
</script>
<script src="/js/vendor/holder.js"></script>
@stop

app/views/admin/users/show.blade.php
@extends('admin.layouts.master')

@section('title')
User Delete
@stop

@section('head')
	
@stop

@section('content')
	
	<div class="row">
		<div class="col-sm-12">
			<br />
			<a href="/admin/users" class="btn btn-default"><i class="glyphicon glyphicon-chevron-left"></i> Back</a>
		</div>
	</div>

	<section class="row">
		<div class="col-sm-12">
			<br />
			<div class="alert alert-warning">
				<p>Are you sure you want to delete <strong>{{$user->fullName()}}</strong>?</p>
			</div>
			{{ Form::model($user, array('route' => array('admin.users.destroy', $user->id), 'method' => 'DELETE')) }}										
				@if($errors->any())
					<div class="alert alert-danger">
						<ul>
							{{ implode('', $errors->all('<li class="error">:message</li>')) }}
						</ul>
					</div>
				@endif

				<div class="col-sm-6"> 
					<div class="form-group">
						{{ Form::label('first_name', 'First Name *') }}
						{{ Form::text('first_name', null, array('placeholder' =>'First Name', 'class' => 'form-control')) }}
					</div>
				</div>
				<div class="col-sm-6">
					<div class="form-group">
						{{ Form::label('last_name', 'Last Name *') }}
						{{ Form::text('last_name', null, array('placeholder' =>'Last Name', 'class' => 'form-control')) }}
					</div>
				</div>

				<div class="col-sm-6"> 
					<div class="form-group">
						{{ Form::label('email', 'Email *') }}
						{{ Form::text('email', null, array('placeholder' =>'Email', 'class' => 'form-control')) }}
					</div>
				</div>

				<div class="form-group pull-right">			
					{{ link_to('admin/users', 'Cancel',  array('class' => 'btn btn-danger')) }}
					{{ Form::submit('Delete', array('class' => 'btn btn-warning')) }}
				</div>

			{{ Form::close() }}
					
		</div>
		
	 </section> <!-- /.container -->
@stop

@section('script')

@stop